### ISSUE TITLE
Unclear on which driver is required

### ISSUE THREAD

**Issue by knivd** [zorkzorkus/ZorkPicUSB#2]
The example works fine and a device called 'PIC32MZ USB' enumerates in Windows, however, I am unable to determine which driver needs to be installed in order to perform data transfer. Testing through terminal, so probably a serial port?

**Comment by zorkzorkus** [comment]
The device enumerates with a "vendor specific" interface (0xFF, // bInterfaceClass - Vendor Specific) and is intended to use with libusb or WinUSB.

You can use [Zadig](https://zadig.akeo.ie/) or the Windows dialog to install the driver.
![image](https://github.com/zorkzorkus/ZorkPicUSB/assets/7151192/7a8f4065-63f1-4eba-8a82-1c54274a10f2)

I then use [ZorkLibUSB](https://github.com/zorkzorkus/ZorkLib) as a wrapper around libusb to access the device.

**Comment by knivd** [comment]
Is there an easy way for it work as a standard virtual serial device, even the driver is manually installed?

**Comment by zorkzorkus** [comment]
It requires the implementation of the usb-cdc protocol, similar to this example:
[https://github.com/majbthrd/pic16f1454-bootloader/tree/master/example-apps/minimalCDC](https://github.com/majbthrd/pic16f1454-bootloader/tree/master/example-apps/minimalCDC)
The descriptors have to be modified/added and a number of control-transfer callbacks have to be implemented.
Then the "USB Serial Device" driver and tools like PuTTY would work.

**Comment by knivd** [comment]
Thank you
